### ISSUE TITLE
Reporte_EnterpriseA

### ISSUE THREAD

**Issue by Brisa-4** [SistemasTecTlaxiaco/practica-architect-Brisa-4#1]
[Reporte_EnterpriseA.pdf](https://github.com/SistemasTecTlaxiaco/practica-architect-Brisa-4/files/7167185/Reporte_EnterpriseA.pdf)

**Comment by AndreLuna6** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
